### ISSUE TITLE
blaze spawners in overworld = overworld fires!!

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#100]
![image](https://user-images.githubusercontent.com/5810363/68978775-be416880-07c9-11ea-8cce-79498f61ef17.png)

**Comment by demethan** [comment]
ebwizardry is the mod

![image](https://user-images.githubusercontent.com/5810363/68982448-0b770780-07d5-11ea-9623-51ef19eea001.png)

**Comment by slidingmike** [comment]
Might be a config change. If it is, we can adjust.

**Comment by topher2010** [comment]
I didn't see anything about spawners in the config

**Comment by demethan** [comment]
Also note that this blaze spawner, the blazes drop nothing.

**Comment by slidingmike** [comment]
Can confirm, there's no way to control this in the config. Will need to discuss if we want to turn off fire tick on the server or live with it, but no changes can be made for the pack.
