### ISSUE TITLE
wither cats are still enabled.

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#101]
![image](https://user-images.githubusercontent.com/5810363/68980965-f8ae0400-07cf-11ea-8f51-2bfc5cf60e2a.png)

**Comment by slidingmike** [comment]
Yeah, I’m not getting this one. It’s disabled client side, this maybe an issue with duplicate configs on the server.

Toph, can you check the enderzoo config

**Comment by topher2010** [comment]
# Biggest spawn group. [range: 0 ~ 32, default: 1]
    I:maxSpawnCount=0

    # Smallest spawn group. [range: 0 ~ 32, default: 1]
    I:minSpawnCount=0
    # Configures the spawning frequency. Higher numbers mean more spawns. [range: 0 ~ 100, default: 1]
    I:weightProbability=0

That's the only thing I see being set to disable this spawning.  Not sure if this config is working properly.  Will need to test

**Comment by topher2010** [comment]
Looks like wither witches can spawn with cats, which is most likely the culprit.  Turned off wither witch pets to accommodate this issue.
