### ISSUE TITLE
World Gen: JEI for osmium not showing. Need to regen, I think. 

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#102]
![image](https://user-images.githubusercontent.com/5810363/68988178-80603680-0801-11ea-9b93-c45502fcd11c.png)
![image](https://user-images.githubusercontent.com/5810363/68988187-8c4bf880-0801-11ea-9134-f844520e5b72.png)

top image is gold, bottom image is osmium

**Comment by Bulluk** [comment]
Osmium does spawn though, found a decent amount.
But it is less than default, this was intended (i think)

**Comment by slidingmike** [comment]
Osmium is generating. Not sure why JEI doesn’t pick this up. It is slightly turned down but has been upped since initial server creation.

**Comment by slidingmike** [comment]
I've created a new profile and included the json in the file. This should fix the missing graphs.

**Comment by slidingmike** [comment]
Topher, I'm going to send you the new version. Can you see if you can use this command, run it on 50-100 chunks, and capture the json file it adds? 

https://github.com/way2muchnoise/JustEnoughResources/wiki/Profiling

It just keeps crashing for me.

**Comment by slidingmike** [comment]
This has been fixed.
