### ISSUE TITLE
Mod Suggestion: Mod Name Tooltip (QoL)

### ISSUE THREAD

**Issue by Bulluk** [BreakfastCraft/Spilled-Juice-Modpack#104]
Shows which mod items are from in inventories

https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip

**Comment by slidingmike** [comment]
Approved

**Comment by topher2010** [comment]
Added in 0.0.7

**Comment by Bulluk** [comment]
this was added but removed again. please re-add
