### ISSUE TITLE
not sure what breaks this.  Option key labels are  offset.

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#108]
![image](https://user-images.githubusercontent.com/5810363/68994813-11143200-0855-11ea-9bcb-c8329b1b0e0f.png)

**Comment by slidingmike** [comment]
Perhaps I’m lost on this one, but what exactly is the issue?

**Comment by slidingmike** [comment]
Unable to reproduce or find a fix. Seems changing text size via ingame would be the solution.
