### ISSUE TITLE
TheOneProbe is not  on/configured by default. you need to craft it. 

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#109]
![image](https://user-images.githubusercontent.com/5810363/68995012-0064bb80-0857-11ea-85d4-a61b7d08f6be.png)

**Comment by slidingmike** [comment]
Not sure how this is an issue. Check config

**Comment by slidingmike** [comment]
Updated config to exclude the need for the probe. Also edited location of the dialog.
