### ISSUE TITLE
recipe conflicts

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#110]
![image](https://user-images.githubusercontent.com/5810363/68999452-5e60c580-088e-11ea-975d-8ea879a250cb.png)

![image](https://user-images.githubusercontent.com/5810363/68999456-64ef3d00-088e-11ea-98a7-db514c7c2bd4.png)

**Comment by demethan** [comment]
![image](https://user-images.githubusercontent.com/5810363/68999462-77697680-088e-11ea-86b8-5f5f89e4933d.png)

![image](https://user-images.githubusercontent.com/5810363/68999609-c57f7980-0890-11ea-8e6d-76c43dedd2a8.png)

**Comment by slidingmike** [comment]
Topher is going to look into changing the foundation common config to make gears required in the middle. This should fix the conflict.

**Comment by topher2010** [comment]
Working on fixing the copper, tin, and bronze gears as well since they don't have crafting table recipes currently

**Comment by topher2010** [comment]
Config was changed to require gears in the middle to resolve the conflict.  Also added crafting table recipes for Tin, Copper, and Bronze gears.
