### ISSUE TITLE
diamond spawn rate seems low.

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#111]
harder then vanilla to find diamonds.

**Comment by slidingmike** [comment]
Vanilla ore generation was not changed. I may need to look into vanilla ore being spawned with COFH generation.

**Comment by demethan** [comment]
On the same note.. gold is hard to find too.

**Comment by slidingmike** [comment]
Vanilla ores have been moved to cofh generation. Quark default world options were turned off. Cluster size and counts were updated for gold, diamond, lapis, and emerald.
