### ISSUE TITLE
arcane arsenal for arcane archives/botania interop

### ISSUE THREAD

**Issue by mote** [BreakfastCraft/Spilled-Juice-Modpack#115]
In Arcane Archives book, it mentions needing Arcane Arsenal for some feature interop w/ Botania.
Looks like a thing that's disabled by default
https://www.curseforge.com/minecraft/mc-mods/arcane-archives/files/2753187

Might be rather beta, but let's try it out while we're still testing!

**Comment by Winrylive** [comment]
Oooh, I wonder if it interacts with Corporea Networking! That would totally rock!

**Comment by slidingmike** [comment]
B:"Enable Arsenal"=true
