### ISSUE TITLE
add most seeds to Industrial Squeezer for plant oil?

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#116]
Only vanilla, and IE plants make plant oil.

**Comment by slidingmike** [comment]
Tofu, we may be able to do this via modtweaker and crafttweaker. Wanna see what you can figure out?

**Comment by topher2010** [comment]
I found out how to do it, will just take me a little time to get the scripts written up, figure out power requirements, and test

**Comment by topher2010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add seeds to squeezer recipes](https://trello.com/c/k0K5yOMn/253-add-seeds-to-squeezer-recipes)

**Comment by topher2010** [comment]
Added XLFoods and Rustic seeds to IE Squeezer

**Comment by slidingmike** [comment]
Keeping this open until 0.10 release
