### ISSUE TITLE
Replace Woot with Deep Mobs Learning

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#119]

**Comment by slidingmike** [comment]
Should this replace both woot and tiny mob farm?

**Comment by NiSiSuinegEht** [comment]
Add in [Thaumic Additions](https://www.curseforge.com/minecraft/mc-mods/thaumic-additions) as a magical variant for mob farming, and get rid of Woot and tiny Mob Farms.
