### ISSUE TITLE
ore excavation on client side is not the same as server side!?

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#121]
# Blocks blacklisted from being excavated [default: ]
    S:"Block Blacklist" <
        minecraft:dirt
        minecraft:grass
        minecraft:stone
        minecraft:cobblestone
        minecraft:gravel
        minecraft:sand
        appliedenergistics2:sky_stone_block
        minecraft:stone:1
        chisel:marble2
        minecraft:stone:3
        chisel:limestone2
        minecraft:stone:5
        minecraft:hardened_clay
        minecraft:stained_harden_clay
        minecraft:stained_harden_clay:1
        minecraft:stained_harden_clay:2
        minecraft:stained_harden_clay:3
        minecraft:stained_harden_clay:4
        minecraft:stained_harden_clay:5
        minecraft:stained_harden_clay:6
        minecraft:stained_harden_clay:7
        minecraft:stained_harden_clay:8
        minecraft:stained_harden_clay:9
        minecraft:stained_harden_clay:10
        minecraft:stained_harden_clay:11
        minecraft:stained_harden_clay:12
        minecraft:stained_harden_clay:13
        minecraft:stained_harden_clay:14
        minecraft:stained_harden_clay:15
        minecraft:stonebrick
     >

**Comment by slidingmike** [comment]
Issue with duplicate configs. Will be fixed in 0.0.9, not a pack problem, server problem.
