### ISSUE TITLE
balance ore cost for plates between hammers

### ISSUE THREAD

**Issue by mote** [BreakfastCraft/Spilled-Juice-Modpack#122]
embers hammer needs 2 ore per plate, tinkers hammer needs one ore per plate.
the hammers are equally expensive, so tinkers hammer is the clear choice,

**Comment by NiSiSuinegEht** [comment]
Tinkers isn't in the pack, though.

**Comment by slidingmike** [comment]
Tofu, can you establish aligning these recipes?

**Comment by topher2010** [comment]
Still working on this.  3 iron ingots into 3 iron plates is the only one I haven't figured out how to remove yet, mainly because I have no idea what mod is adding it

**Comment by topher2010** [comment]
The plate recipes have been modified so making plates with hammers all cost the same, 2 ingots and a hammer
