### ISSUE TITLE
There is nothing to simulate a right click. 

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#124]
Trying to automate Astral Sorcery and there are no block to do it. 

Need a mech user or (extUtils or TE) 

block placer don't work

**Comment by NiSiSuinegEht** [comment]
Thaumcraft golems can do it, via the "Use" command seal.

**Comment by slidingmike** [comment]
AutoHotkey can do the work.

**Comment by slidingmike** [comment]
I think BC adds robots, and open computers has robots.

**Comment by demethan** [comment]
We should add Cyclic.

**Comment by Winrylive** [comment]
I 2nd this. Not just for the auto user.

**Comment by slidingmike** [comment]
Cyclic has been denied. 

Drones has tech right click ability, and thaum has magic right click ability.
