### ISSUE TITLE
0.0.9: mining dim: oregen tweaking

### ISSUE THREAD

**Issue by mote** [BreakfastCraft/Spilled-Juice-Modpack#130]
everything feels fine except diamonds which are way too rare.

attaching screenshots from 1-chunk quarry and 2-chunk quarry:

![2019-11-27_17 35 46](https://user-images.githubusercontent.com/334995/69770675-d48ee300-113e-11ea-9a4e-636276189f4e.png)
![2019-11-27_17 45 00](https://user-images.githubusercontent.com/334995/69770676-d48ee300-113e-11ea-89df-5abc652f0f38.png)

**Comment by slidingmike** [comment]
Slight increase to diamonds in 0.10
