### ISSUE TITLE
0.0.9 TF oregen

### ISSUE THREAD

**Issue by mote** [BreakfastCraft/Spilled-Juice-Modpack#131]
Destabilized Redstone, Resonant Ender, and Energized Glowstone have no use in recipes, but are being generated.  They can be disabled in Thermal Foundation

**Comment by slidingmike** [comment]
Unable to locate a way to disable generation of these fluids via configs for thermal foundation or cofh core.

**Comment by slidingmike** [comment]
Thermal Foundation has been removed to fix this.
