### ISSUE TITLE
Magnetic Craft: add fuels to the fuel mod

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#133]
I will attempt to add the magneticcraft fuels to IC2

**Comment by demethan** [comment]
"fuel_dense",4,2
"fuel_light",2,16
"fuel_gaseous",1,8
"heavy_oil",5,2
"light_oil",2,12
"naphtha",1,10
"lpg",1,6
"natural_gas",1,6


change in the additionalFuels.csv

**Comment by demethan** [comment]
Should I add biodiesel?

**Comment by demethan** [comment]
fuck it,  I added every fuel I found.

"fuel_dense",4,2
"fuel_light",2,16
"fuel_gaseous",1,8
"heavy_oil",5,2
"light_oil",2,12
"naphtha",1,10
"lpg",1,6
"wood_gas",1,4
"natural_gas",1,6
"biodiesel",4,3
"biofuel",3,3
"syngas",1,10

**Comment by slidingmike** [comment]
This will be added in 0.10
