### ISSUE TITLE
lv coil recipe with IC2 wires?

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#135]
8 copper cable  around a stick?
![image](https://user-images.githubusercontent.com/5810363/69906604-03ea5d80-1394-11ea-8518-30616b8a059d.png)

**Comment by slidingmike** [comment]
Topher, can you do this? 8 copper ic2 cable and equal the recipe above?

**Comment by topher2010** [comment]
8 uninsulated copper wire surrounding a treated stick added.
