### ISSUE TITLE
fluix crystal can only be grinded in the hand grinder. 

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#138]
there are no recipe for grinding the fluix crystal.  Weird.

**Comment by demethan** [comment]
same for the AE quartz crystal
![image](https://user-images.githubusercontent.com/5810363/69931239-83f7ec80-1494-11ea-81f4-de881d1fdbb6.png)

![image](https://user-images.githubusercontent.com/5810363/69931254-92de9f00-1494-11ea-8178-79160599be59.png)

**Comment by slidingmike** [comment]
modintegration {
    S:CraftTweaker=ON
    S:IndustrialCraft2=ON
    S:InventoryTweaks=ON
    S:JustEnoughItems=ON
    S:Mekanism=OFF
    S:MineFactoryReloaded=OFF
    S:OpenComputers=ON
    S:Railcraft=OFF
    S:Tesla=OFF
    S:TheOneProbe=ON
    S:Waila=OFF
}

Testing to see if this will work if we will need to do custom configs. Assigning to Topher, but hold until confirmation is made. (Basic recipe for Macerator, whatever IE has for grinder, etc)

**Comment by topher2010** [comment]
IC2 Macerator can now grind Fluix crystal, Certus quartz crystal, Certus Quartz ore, and sky stone block.  I also added recipes to Nether quartz and Nether quartz ore.  Ender Pearl was also added to the Macerator.

**Comment by topher2010** [comment]
IE Crusher has these same recipes now as well

**Comment by topher2010** [comment]
Magneticraft Crusher recipes added as well.  @slidingmike do we keep this open or close it?
