### ISSUE TITLE
Script Changes

### ISSUE THREAD

**Issue by slidingmike** [BreakfastCraft/Spilled-Juice-Modpack#139]
Iron Gear has two recipes
1. 4 Iron around Stone Gear - Keep
2. 5 Iron in Gear Shape - Remove

Diamond Gear should be changed
1. 4 diamond around iron gear (not iron ingot as currently)

Wooden Gear for AE2 (has a conflict with wooden gears from Foundation)
1. 4 sticks around cobblestone instead of just 4 sticks

Recipes can be removed for: (Confirmed none show "uses" in JEI)
Emerald Gear
Lead Gear (Normal and IE if possible)
Aluminum (Normal and IE if possible)
Silver (Normal and IE if possible)
Nickel (Normal and IE if possible)
Platinum (Normal and IE if possible)
Iridium (Normal and IE if possible)
Mana Infused (Normal and IE if possible)
Steel (Normal and IE if possible)
Electrum (Normal and IE if possible)
Invar (Normal and IE if possible)
Constantan (Normal and IE if possible)
Signalum (Normal and IE if possible)
Lumium (Normal and IE if possible)
Enderium (Normal and IE if possible)

**Comment by topher2010** [comment]
Done as requested

**Comment by slidingmike** [comment]
So pretty much all of this is no longer needed with the removal of thermal foundation. There are a few that we need to pursue though.

1. Wooden Gear for AE2 (has a conflict with wooden gears from buildcraft): 4 sticks around cobblestone instead of just 4 sticks
2. Is there any way to oredict the diamond gear from BC with the diamond gear from tesla core lib?
3.Bronze Gear for Forestry should be 4 bronze around iron gear from tesla core lib
4.Copper Gear for Forestry should be 4 copper around iron gear from tesla core lib
5.Tin Gear for Forestry should be 4 tin around iron gear from tesla core lib.

Plates also need some work from the previous requirements

All of the ic2 are showing 2 ingots per hammer so that's perfect

1. aluminium plate from IE needs an ic2 hammer with 2 ingot recipe 
2. silver plate from IE needs an ic2 hammer with 2 ingot recipe
3. nickel plate from IE needs an ic2 hammer with 2 ingot recipe 

Thaumcraft has some plates (brass plate, thaumium plate, void metal plate)
All of these need to be 2 ingot with ie hammer, 2 ingot with ic2 hammer, (one ingot in ic2 metal former)
All of these need to have the 3 ingot recipe remove if possible

Thaumic Additions should mimic the above Mithrillium Plate, Adaminite Plate, Mithminite Plate

**Comment by topher2010** [comment]
Removed Thermal Foundation gear recipe changes.
