### ISSUE TITLE
0.0.11 - iron gear recipe broken

### ISSUE THREAD

**Issue by mote** [BreakfastCraft/Spilled-Juice-Modpack#147]
stone gear to iron gear recipe needs to use any stone gear.

**Comment by UnNinja** [comment]
is that related to [this](https://github.com/BreakfastCraft/Spilled-Juice-Modpack/issues/139), or a separate issue?

**Comment by mote** [comment]
the changes there probably introduced this bug.
4 iron around stone gear currently doesn't work. our current stone gear recipe creates buildcraft gear, i suspect the recipe is set to use tesla's gear

**Comment by mote** [comment]
gold gear is in the same boat

**Comment by slidingmike** [comment]
Resolved with updated scripts
