### ISSUE TITLE
Request:  Malisis Doors or similar.

### ISSUE THREAD

**Issue by NiSiSuinegEht** [BreakfastCraft/Spilled-Juice-Modpack#149]
For a long term pack, cosmetics can make a big difference in the desire of certain players to keep going.  Something similar to Malisis Door, such as LittleTiles, can greatly improve quality of life.  Malisis doors has an integrated system for making doors that simply cannot be replicated with other mods, such as player detecting vanishing barriers, 3x3 door spaces, etc.

**Comment by slidingmike** [comment]
Ugh

**Comment by UnNinja** [comment]
https://www.curseforge.com/minecraft/mc-mods/littletiles
