### ISSUE TITLE
recipe conflict - advanced genenerator iron frame

### ISSUE THREAD

**Issue by OneChipBob** [BreakfastCraft/Spilled-Juice-Modpack#155]
only one recipe displays and it is for the aether's iron ring

iron ring from crafting table
![IronRing](https://user-images.githubusercontent.com/25930058/70957737-0e1f8380-2045-11ea-841a-2346d3f1fcf2.PNG)

iron frame from jei
![IronFrame](https://user-images.githubusercontent.com/25930058/70957753-20012680-2045-11ea-82a4-ef02adcab26f.PNG)

**Comment by topher2010** [comment]
fixed, file sent to @slidingmike

**Comment by slidingmike** [comment]
Implemented in 1.0
