### ISSUE TITLE
steel plate creation

### ISSUE THREAD

**Issue by OneChipBob** [BreakfastCraft/Spilled-Juice-Modpack#157]
steel plate is needed to make immersive engineering plate mold to be used with the metal press

only available recipes are from IC2 or the immersive engineering metal press

![steelPlate](https://user-images.githubusercontent.com/25930058/70961166-04028280-204f-11ea-9cdf-7f6391fa4a2f.PNG)

**Comment by topher2010** [comment]
Added 2 ingots and IC2/IE Hammer to one plate recipes

**Comment by slidingmike** [comment]
Implemented in 1.0 release
