### ISSUE TITLE
Item Render Crash twice now

### ISSUE THREAD

**Issue by MitoniKatsu** [BreakfastCraft/Spilled-Juice-Modpack#16]
[crash-2016-02-03_00.47.05-client.txt](https://github.com/slidingmike/Spilled-Juice-Modpack/files/116053/crash-2016-02-03_00.47.05-client.txt)
[crash-2016-02-03_12.19.59-client.txt](https://github.com/slidingmike/Spilled-Juice-Modpack/files/116054/crash-2016-02-03_12.19.59-client.txt)

Both times I was scrolling through pages in the openblocks book.

**Comment by Lunchington** [comment]
Looks like a forestry bug. Almost the exact same error.

https://github.com/ForestryMC/ForestryMC/issues/1050

**Comment by slidingmike** [comment]
We can update to their dev version and see what happens. I'll be monitoring the referenced thread until confirmation of this being fixed.

**Comment by slidingmike** [comment]
Reference shows the dev version fixes the issue. We will add the dev verson to the next update 1.2.2
