### ISSUE TITLE
Mod Suggestions/Requests (Glass and Water)

### ISSUE THREAD

**Issue by zOwenn** [BreakfastCraft/Spilled-Juice-Modpack#164]
**Extra Glass**
https://www.curseforge.com/minecraft/mc-mods/extra-glass
Adds some of the Extra Utilities style glass (dark, clear, luminous etc...) - no other mod seems to add dark glass, and any existing clear glass isnt really clear glass.

**Bubble column elevator backport**
https://www.curseforge.com/minecraft/mc-mods/bubble-column-elevator-backport
Adds some of the 1.13 water mechanics (currently only the magma block/soul sand water elevators) - nice for some simple elevators when ender pearls are low.

**Comment by UnNinja** [comment]
Does extra glass have the same problem has that workstation mod we pulled (using code from existing mods rather than starting from scratch)?
I like the idea of bubble streams being an option

**Comment by zOwenn** [comment]
Im not sure on the extra glass thing - don't know what problems you had with that workstation mod. I've looked at source code and stuff and cant find the glass code in xu2 to compare to

**Comment by slidingmike** [comment]
Bubble Columns implemented in new version.

No go on Extra Glass (See ArchitectureCraft for better glass options/panes)
