### ISSUE TITLE
mod requests

### ISSUE THREAD

**Issue by UnNinja** [BreakfastCraft/Spilled-Juice-Modpack#165]
[Engineer's decor](https://www.curseforge.com/minecraft/mc-mods/engineers-decor)
several nice functional and cosmetic additions to IE

[Integrated tunnels](
https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels), [integrated crafting](https://www.curseforge.com/minecraft/mc-mods/integrated-crafting), [integrated ternimals](https://www.curseforge.com/minecraft/mc-mods/integrated-terminals)
adds additional functionality to integrated dynamics. tunnels allows it to move items/fluids/power, crafting lets it support autocrafting, terminals allows things to be managed more easily (and serve as a storage system)

**Comment by slidingmike** [comment]
Added all

**Comment by UnNinja** [comment]
you added you added https://www.curseforge.com/minecraft/mc-mods/engineers-doors instead of https://www.curseforge.com/minecraft/mc-mods/engineers-decor
