### ISSUE TITLE
recipe conflict

### ISSUE THREAD

**Issue by UnNinja** [BreakfastCraft/Spilled-Juice-Modpack#166]
[roots knives](https://i.imgur.com/GoR0o5L.png) and [literal ascension carving tools](https://i.imgur.com/ldQ2N4J.png)
both also have stone/iron/diamond/gold versions, same conflict

**Comment by topher2010** [comment]
@UnNinja will need suggested recipe changes

**Comment by UnNinja** [comment]
i guess. swap the stick and whatever is in the top corner for carving tools https://i.imgur.com/zbjpJ95.png
anything I can think of that makes more sense conflicts with something else
