### ISSUE TITLE
Potion id conflict

### ISSUE THREAD

**Issue by ghost** [BreakfastCraft/Spilled-Juice-Modpack#17]
Botania advanced potion flasks grant effects that they are not meant to.
Example: flask of marine allure grants Yellow Curse from Aura Cascade instead of desired effect.
[potion.txt](https://github.com/BreakfastCraft/Spilled-Juice-Modpack/files/119783/potion.txt)

**Comment by Lunchington** [comment]
Changed the botnai potion iD's 

should fix the issue. 

#https://github.com/BreakfastCraft/Spilled-Juice-Modpack/commit/37db12d259cc9abe5dc433d044e5e7fd58952a68

**Comment by slidingmike** [comment]
Update via Client Side Configuration Files

**Comment by slidingmike** [comment]
Fixed in 1.3.1
