### ISSUE TITLE
Config change request: Chisels and Bits - Increased Bit in Chiseled Bag 

### ISSUE THREAD

**Issue by Bulluk** [BreakfastCraft/Spilled-Juice-Modpack#170]
per stack you can hold 512 bits, i suggest this gets increased to 4096. (which is 1 full block of bits)

line 4 of the chiselsandbits.cfg
    I:bagStackSize=512 >     I:bagStackSize=4096

**Comment by UnNinja** [comment]
that much stack size seems asking for trouble. maybe 2048 (or even1024) instead of 4096?

**Comment by slidingmike** [comment]
1024
