### ISSUE TITLE
OreDict Request: IC2 Rubber <-> IF Plastic

### ISSUE THREAD

**Issue by Bulluk** [BreakfastCraft/Spilled-Juice-Modpack#173]
IC2 crafting recipes accept IF plastic, but IF crafting recipes do not accept IC2 rubber

**Comment by UnNinja** [comment]
No. IF plastic is its own process now, not just a different flavor of rubber like in the mfr days. IC2 accepting plastic is probably a bug, but it's either #cantfix or #wontfix.
