### ISSUE TITLE
Mod Request:  Soul Shards Respawn

### ISSUE THREAD

**Issue by NiSiSuinegEht** [BreakfastCraft/Spilled-Juice-Modpack#177]
Since there is a lack of non-tech spawner changing mods for player kill farming, I humbly request this one be added.

https://www.curseforge.com/minecraft/mc-mods/soul-shards-respawn

Note:

> Modpacks
> Soul Shards Respawn can be used any modpack. If you still ask me, I will say you can't use it.

**Comment by slidingmike** [comment]
Ninjer said no, and ninjer with the flu is a beast unable to be conquered.

**Comment by slidingmike** [comment]
Added Mob Grinding Utils to appease the masses
