### ISSUE TITLE
Mod request: Dark Utilities

### ISSUE THREAD

**Issue by NiSiSuinegEht** [BreakfastCraft/Spilled-Juice-Modpack#179]
We lack a mod with reliable mob movement capabilities, so I'm proposing the addition of [Dark Utilities](https://www.curseforge.com/minecraft/mc-mods/dark-utilities).

**Comment by UnNinja** [comment]
IF conveyor belts, openblocks fan, that fan flower from botania, pneumaticraft blower pipe thingy, portals?
