### ISSUE TITLE
irridium: EU requirement too high.

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#23]
18.5 Million is too much EU for iridium . 

One ultimate solar require 64 iridium and it takes me 5 hour to make one.  it was already balanced.

**Comment by demethan** [comment]
12 million EU is still too high and the nerf is kinda pointless at this point.

**Comment by slidingmike** [comment]
Pointless for only you. Everyone else isn't at the point of iridium  being needed. The original thought was iridium only though UU Matter. I added back in the molecule assembler, but still feel 12m is too easy. What's going to happen when you're done with ic2? The pack is over at that point.

**Comment by slidingmike** [comment]
https://github.com/BreakfastCraft/Spilled-Juice-Modpack/commit/8b6d43275ae812075abda8874581367d4b22efd9

change from 18.5 to 12

**Comment by demethan** [comment]
Ok, Ill make due.. thx for reply
