### ISSUE TITLE
IC2 not recognizing other cables for power

### ISSUE THREAD

**Issue by slidingmike** [BreakfastCraft/Spilled-Juice-Modpack#26]
Mekanism Cables,
BC Pipes,
Immersive Engineering Wire

None are recognized or pass power through for ic2. Was working before latest update.

**Comment by demethan** [comment]
did you put in the bridge patch for ic2??

**Comment by slidingmike** [comment]
i wasn't aware there was a bridge patch for such. Any chance of a link for information?

**Comment by slidingmike** [comment]
http://forum.industrial-craft.net/index.php?page=Thread&threadID=10864
