### ISSUE TITLE
EnderIO Fluid Tank

### ISSUE THREAD

**Issue by Sansu11** [BreakfastCraft/Spilled-Juice-Modpack#30]
The fluid tank isn't retaining fluids when broken with wrench's. Regardless of which mods wrench is used.

There are currently no options for portable fluids.

**Comment by slidingmike** [comment]
I think this is a forge issue. I'll see if I can contact the devs and ask.

**Comment by slidingmike** [comment]
Just updated forge from 1254 to 1257. May fix it when 3.0.5 is live. Please confirm or deny once it's live.

**Comment by Sansu11** [comment]
Not fixed.

**Comment by slidingmike** [comment]
Ender IO and Ender Core Updates coming in 3.0.6 Maybe this will work

**Comment by slidingmike** [comment]
Fixed in 3.0.10
