### ISSUE TITLE
Chisel Glass

### ISSUE THREAD

**Issue by Sansu11** [BreakfastCraft/Spilled-Juice-Modpack#31]
So apparently Chisel Glass lets you look through the world. o.o Shows blocks that aren't dirt/sand/gravel ect.

http://i.imgur.com/aN7Jok4.jpg

**Comment by Sansu11** [comment]
_update_

Apparently trying to remove chisel glass causes a hard crash.

**Comment by slidingmike** [comment]
The version we're using is very buggy. It's also from the Unstable Pack. There is no other public update released, so I may have to remove this for the time being.

**Comment by slidingmike** [comment]
Removed for the time being.
