### ISSUE TITLE
Hard Crash when placing Quark Slabs (Thatch)

### ISSUE THREAD

**Issue by Winrylive** [BreakfastCraft/Spilled-Juice-Modpack#33]
Trying to build, man! Thatch and Andesite slabs from Quark cause this if I'm not super-uber careful where to place them.

[crash-2016-07-01_17.13.56-client.txt](https://github.com/BreakfastCraft/Spilled-Juice-Modpack/files/344587/crash-2016-07-01_17.13.56-client.txt)

**Comment by UnNinja** [comment]
Change "B:enableGenerateVertical_slab=" to false in general.cfg in the BuildingBricks folder. We pushed this to the server just before mike left, but apparently it needs to be changed clientside as well. It will be included in the next update.

**Comment by Winrylive** [comment]
Thanks ninja.

**Comment by slidingmike** [comment]
https://github.com/hea3ven/BuildingBricks/issues/84#issuecomment-229389604
