### ISSUE TITLE
IC2 Shaft no recipe in JEI

### ISSUE THREAD

**Issue by waerloga** [BreakfastCraft/Spilled-Juice-Modpack#34]
Typical recipe of block of iron or steel in the compressor to make the shaft of iron or steel is not showing up in JEI. I've not made the IC2 chain to determine if this is an IC2 missing recipe or just a IC2/JEI bug. Most other IC2 recipes are in JEI however.

**Comment by waerloga** [comment]
Ok, I just cheated in some parts it's a missing recipe on the compressor side assuming that's the way to make it.

**Comment by slidingmike** [comment]
I thought the shaft was a metal former recipe and not a compressor.

**Comment by waerloga** [comment]
You are right, I was misremembering. So it just does not show up in JEI nor do IC2 power storage devices allow batteries to be directly inserted, have to pipe them in/out

**Comment by slidingmike** [comment]
I'd report this, but ic2's issue tracker is a pain in the ass and I have no earthly idea if it's been reported yet or not.

**Comment by slidingmike** [comment]
ic2 removed. No longer valid.
