### ISSUE TITLE
Mekanism

### ISSUE THREAD

**Issue by ShalltearFR** [BreakfastCraft/Spilled-Juice-Modpack#44]
Being in search of modpack 1.10, I find your excellent modpack.
However, I was wondering if it is possible to integrate the Mekanism mod.

I give you the link for info:
http://aidancbrady.com/mekanism/download/

Thank you in advance :)

**Comment by UnNinja** [comment]
Hi, thanks for your interest. We're as hyped as the next guy for Mek to be in the pack, but it's only been two days and the dev has already pushed like 5 bugfix updates. We're giving it a couple days for things to settle down before we add it in.

**Comment by UnNinja** [comment]
Mekanism is added as of 0.1.4

**Comment by ShalltearFR** [comment]
Thanks you !
