### ISSUE TITLE
0.1.4.2-0.1.4.1 and Solar Flux Reborn

### ISSUE THREAD

**Issue by MistakesWMade** [BreakfastCraft/Spilled-Juice-Modpack#47]
Just wanted to make a note/ask/bring to attention that as of the removal of IC2, the unrelated Solar Flux Reborn seems to have gone as well. At least, the base for the Solar Flux panels. The mods not entirely gone, just.. Parts of it?
Loving the pack, thank you!

**Comment by UnNinja** [comment]
D'oh! The .1 and .2 hotfixes were pushed out in something of a rush (because crashes are bad), and it seems we accidently a button somewhere during the process <.<
This will be fixed (again) in 0.1.5, which should drop in the next day or three

**Comment by UnNinja** [comment]
Or, you know, I could remember you can edit packs after they're live. Give atl a few minutes to catch up with itself, then reinstall the pack to get the corrected configs.

**Comment by MistakesWMade** [comment]
Thank you for the quick fix!
