### ISSUE TITLE
Translocator Recipe missing.

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#48]
the recipe for the translocator are not showing up in JEI.  I tried to craft them anyways with the old recipe.. no go.

**Comment by UnNinja** [comment]
I was going to bug mike to make a recipe, but I cheated a translocator in and it crashed the game. Seeing as we have the latest version of translocator, I guess we're pulling it out until things are fixed

**Comment by slidingmike** [comment]
https://github.com/TheCBProject/Translocators/issues/1
