### ISSUE TITLE
Crash client to change Version 0.1.4 to 0.1.4.3

### ISSUE THREAD

**Issue by ShalltearFR** [BreakfastCraft/Spilled-Juice-Modpack#50]
Minecraft work but I have a crash client and this error when I connect to the server.
Any problem in server.

http://pastebin.com/RUTRvgtk

**Comment by ShalltearFR** [comment]
Disable JEI, JER and the client does not crash

**Comment by ShalltearFR** [comment]
Problem solved, I deleted the file "ActuallyAdditions-1.10.2-r55.jar" in the "mods" folder.
I handed over the file on the server, I rebooted and more worries.

The "ActuallyAdditions-1.10.2-r55.jar" file from being corrupted.

**Comment by slidingmike** [comment]
Okay. 

So the AA file is preventing SSP from loading for you with JEI and JER enabled, correct? 

Let's take this one step at a time, since I've not got other reports of this issue. (client or server side)

**Comment by ShalltearFR** [comment]
I think JEI did crash the client because the file "ActuallyAdditions-1.10.2-r55.jar" was corrupt.
This is a bad download of my hand, modpack is healthy.
