### ISSUE TITLE
Veinminer

### ISSUE THREAD

**Issue by Yoosk** [BreakfastCraft/Spilled-Juice-Modpack#54]
With the latest 0.1.7 update, veinminer doesn't works with Actually Additions AIOT tools. No idea if that's intended, but it was working well in previous versions. Tested both in SSP and SMP on your server.

**Comment by UnNinja** [comment]
AA just had a couple major updates, this is probably an unintended side effect of one of those. Will be fixed in 0.1.8

**Comment by slidingmike** [comment]
Looks like this is related to the update of AA. I'll check for some information. Our Configs still show them in the config files for veinminer.

**Comment by slidingmike** [comment]
Did we get this fixed @Yoosk ?

**Comment by Yoosk** [comment]
Works just fine now, thanks.
