### ISSUE TITLE
Low fps on this pack

### ISSUE THREAD

**Issue by mkiplm** [BreakfastCraft/Spilled-Juice-Modpack#55]
I installed this on my laptop and it ran smooth as anything. put it on my desktop, and i was getting 1fps. It was so bad i had to put optifine in and turn off all the animations.

My desktop specs are:

Operating System: Windows 10 Pro 64-bit (10.0, Build 10586) (10586.th2_release.160802-1857)
Processor: AMD FX(tm)-8350 Eight-Core Processor            (8 CPUs), ~4.0GHz
Memory: 16384MB RAM
Available OS Memory: 16280MB RAM
Running Ram speed: 2400mhz

Video cards: 2x R9 290x's Crossfired.

And java is up to date and set for 64xbit

So what could be causing this issue?

**Comment by slidingmike** [comment]
Good afternoon. Is this something that's occurred before the update from yesterday, or just after? 

Are you playing an established world on the desktop, or is just a newly loaded SSP?

**Comment by mkiplm** [comment]
I just installed it. then i figure my system was having issues so i reset back to factory with clean install. and  still laggy, and it was on single player world. i was gonna make a server but it would have same out come.

**Comment by mkiplm** [comment]
So i was messing around and it seems to be the terrain animation thats dropping fps so hard.

**Comment by slidingmike** [comment]
Any information on how to fix ?

**Comment by mkiplm** [comment]
Optifine mod. And video settings > Animations Then manually turned off terrain animation

my guess amd, cant handle the animations of the whole map.

**Comment by slidingmike** [comment]
Quite possible. Thank you for the information, I'll record it to let others know. If I happen to find a mod that's causing it (Building Blocks might be a culprit. I'll re open this.)
