### ISSUE TITLE
[Request] Add Aroma1997's Dimensional Mining World Mod

### ISSUE THREAD

**Issue by Winrylive** [BreakfastCraft/Spilled-Juice-Modpack#58]
It's 1.10 now, and there's been requests for a mining world....

https://minecraft.curseforge.com/projects/aroma1997s-dimensional-world

**Comment by slidingmike** [comment]
I'll bug ninja. I know we had problems using rftools in the past.

**Comment by slidingmike** [comment]
Going to try rftools mining dimension first, will re open if it fails again.

**Comment by UnNinja** [comment]
note that journeymap and rftoosl teleporters (and probably a couple other things) are slightly derpy in the version on live. This will be fixed in juice 0.1.15
