### ISSUE TITLE
RFTools Dimensions default dimlets blacklisted.

### ISSUE THREAD

**Issue by ChrisCrisis** [BreakfastCraft/Spilled-Juice-Modpack#62]
Hi, 
when i attempt to create something like a mining dim i was looking around for the diffent dimlets available and notice stuff like Material Default and Liquid default are missing.
Also some of the default dimlets seem to be blacklisted, like SkyDimlet Normal or SkyDimlet NormalDay.

**Comment by UnNinja** [comment]
Oh, bugger. Did mike forget to disable the world builder? _checks_ yes, yes he did. Will be disabled in 0.2, sorry (a mining age will pop up on our servers after a couple weeks)
