### ISSUE TITLE
Pams harvestcraft Mod issue

### ISSUE THREAD

**Issue by Ozimundis** [BreakfastCraft/Spilled-Juice-Modpack#63]
As per request, making an issue here, relating to an issue with Pams harvestfraft not appearing/working serverside. 
https://github.com/MatrexsVigil/harvestcraft/issues/167

**Comment by slidingmike** [comment]
The errors on join  might be something to do with a scripting error in our scripts.zs file. I'll have @F4ndroid take a look to make sure there's no issue on that side.

**Comment by slidingmike** [comment]
The crash is related to a NPE on rendering for a Tinker's Block:

"Screen name: slimeknights.tconstruct.tools.common.client.GuiCraftingStation"

They'll need a copy of that crash report in their github to resolve that problem

**Comment by slidingmike** [comment]
I'm not having any issues with .15 on looking up @pam or @harvest Are we sure that the server owner did a proper update?

**Comment by Ozimundis** [comment]
We're renting our server through the company "Creeperhost".
They have, what I guess you'd call a 1 click installation system for most packs, including Spilled Juice. 
I can ask them if it might be something on their end? 
Anything you could suggest I ask them, pertinent information, etc?
Edit, I can always try uploading the version of Pams directly from my pc. 
Download it from curse, then upload it to the server?

**Comment by slidingmike** [comment]
You'll want to make sure that within the mod folder Pam's does exist. The version 0.15 is using is, 1.9.4-1.10.2d. If Creeperhost support can confirm it exists, we've gotta do a bit more digging, but in regards to your edit, yes you can.

**Comment by Ozimundis** [comment]
Ok, I've just looked, the file does exist on the server, and it's the correct version, however, the file size is only 4kb. Thiink I might have found what the issue is.. 

I'll try uploading the file myself, from the instance folder of spilled juice to the server, then see if that fixes things. 
And let Creeperhost know they messed up the installation.

**Comment by slidingmike** [comment]
Sounds good, I'll leave this open until you've confirmed it's working in game. Glad we could help resolve the issue.

**Comment by Ozimundis** [comment]
That seems to have done it! thank you for taking the time to help me, I shall forward the Error Repo onto the Tinkers guys. :+1:
