### ISSUE TITLE
Mod Suggestions: Bagel 2

### ISSUE THREAD

**Issue by Winrylive** [BreakfastCraft/Spilled-Juice-Modpack#64]
https://minecraft.curseforge.com/projects/bagginses

https://minecraft.curseforge.com/projects/realistic-terrain-generation

https://minecraft.curseforge.com/projects/router-reborn

**Comment by UnNinja** [comment]
1: Maybe. There are a couple backpack mods that play extra nice with the grave mod, might use one of them. Requires investigation.

2: Not toaster friendly, and we have plenty of people with toasters. Quark adds a realistic gen option, probably going to use that

3: Most probably

**Comment by slidingmike** [comment]
Three is currently in discussion for another project, problem is it's almost redundant currently. Will discuss.

**Comment by slidingmike** [comment]
I'm fine with number one.

**Comment by slidingmike** [comment]
https://minecraft.curseforge.com/projects/industrial-craft

**Comment by slidingmike** [comment]
AByssalcraft needs to go

**Comment by UnNinja** [comment]
Once I have a list I'll make a separate thing for things to die in a fire

**Comment by slidingmike** [comment]
Storage Network needs death.

**Comment by Winrylive** [comment]
> Quark adds a realistic gen option, probably going to use that

Didn't know that, I'll have to look for snapshots of what that looks like.  Just looked it up, that would be great!

**Comment by zOwenn** [comment]
Hm. Ya-know, us people who have fallen victim to login deaths? :P https://minecraft.curseforge.com/projects/login-shield

**Comment by zOwenn** [comment]
Oh, and just something that could be helpful for we who are noobs with mods, Enchiridion. So we can keep all our books in the same place!
https://minecraft.curseforge.com/projects/enchiridion

**Comment by UnNinja** [comment]
We already have [a mod](https://minecraft.curseforge.com/projects/akashic-tome) to condense books into one place (one for [wrenches](https://minecraft.curseforge.com/projects/morph-o-tool) too)
Login shield is indeed probably something we can make use of

**Comment by slidingmike** [comment]
Yes to login shield, I'm also indifferent on the enchiridion. its a great mod as it is.

**Comment by Winrylive** [comment]
World seed I'd like to submit for possible use: 293684955496910001

http://imgur.com/a/r6QoZ

It has desert, savannah, forest, ocean, and taiga as well as a village within a 200 blk distance of spawn.

**Comment by Winrylive** [comment]
Mystical Agriculture: move to disable flight from Supremium armor.

**Comment by StaticPH** [comment]
I don't know if there is anyone who actually uses these mods, but if there isn't we should just trim them from the pack:
-AdChimneys
-Bagelsmore
-CustomDrones
-MalisisDoors
-MalisisBlocks
-MalisisCore(assuming above pair)
-Platforms(Why not just use chisels&bits anyways?)

Additionally, I'd like to add:
-[Cooking for Blockheads](https://minecraft.curseforge.com/projects/cooking-for-blockheads)
-[Tinkers Tool Leveling](https://minecraft.curseforge.com/projects/tinkers-tool-leveling)
-[Not Enough Wands](https://minecraft.curseforge.com/projects/not-enough-wands)
-[Similsax Transtructors](https://minecraft.curseforge.com/projects/similsax-transtructors)
-[Super Multi-Drills](https://minecraft.curseforge.com/projects/super-multi-drills)
-[MmmMmmMmmMmm](https://minecraft.curseforge.com/projects/mmmmmmmmmmmm)
-[Visible Armor Slots](https://minecraft.curseforge.com/projects/visible-armor-slots)
-[Experience Rings](https://minecraft.curseforge.com/projects/experience-rings)

**Comment by UnNinja** [comment]
Malisis is staying, as it platforms ([rest are already gone](https://github.com/BreakfastCraft/Spilled-Juice-Modpack/issues/65))
As for the additions; yes, yes, no, no, no (freeze), no, yes, no

**Comment by F4ndroid** [comment]
Move to keep Advanced Chimneys. They're amazing.

**Comment by StaticPH** [comment]
Why no MmmMmmMmmMmm?

**Comment by UnNinja** [comment]
Because mike.
Close enough to the update that I'm going to stop taking suggestions (though they seem to have dried up anyway)
