### ISSUE TITLE
Mod removals: Bagel 2

### ISSUE THREAD

**Issue by UnNinja** [BreakfastCraft/Spilled-Juice-Modpack#65]
Current list:
Abyssalcraft, Autopackager, CustomDrones, CraftingCraft, Colossal Chests, Silimatics, ZenModLoader, Bagelsmore: The Return, Persistant Bits (does silly things from time to time. stick with exu2 and ftbu)
Bagginses (moving to a different bag mod)
Storage Network, Capluse, QuantumStorage, EnderThing (transitioning to a different enderchest mod)
SimpleCovers, ForgeEnderTech, Advanced Chimneys, 
Agricultural Expansion (going to a different magical crops mod)

See something you want to stay in? Want something else to go? Make your case here

**Comment by F4ndroid** [comment]
Colossal Chests is fun. Why is it being removed?

**Comment by slidingmike** [comment]
Just unneeded for the pack.
