### ISSUE TITLE
Chisel Marble

### ISSUE THREAD

**Issue by zOwenn** [BreakfastCraft/Spilled-Juice-Modpack#66]
For some reason Raw Marble from chisel is spawning very rarely and as single block geodes, wouldnt mind building with marble :)

**Comment by slidingmike** [comment]
Normally marble is disabled completely. I hate it. I'll see if we can turn it up.

**Comment by Winrylive** [comment]
I would  have loved to use it too, but with its rarity I opted for Extra Blocks marble. It's not as smooth but it does the trick.

**Comment by UnNinja** [comment]
Marble spawning rate restored to default rate (roughly 3x what is is now) in 0.2.3
