### ISSUE TITLE
Client Fatal crash from combining ender tank with immersive engineering tubes

### ISSUE THREAD

**Issue by xondk** [BreakfastCraft/Spilled-Juice-Modpack#68]
If you place down an ender tank, and put an immersive engineering tube on the side of it, this will clash client, (not server, server is not reporting any issues), and client will effectively be unable to log in again, because of it.

---

[crash-2016-10-11_13.00.31-client.txt](https://github.com/BreakfastCraft/Spilled-Juice-Modpack/files/521643/crash-2016-10-11_13.00.31-client.txt)

**Comment by UnNinja** [comment]
Are you using optifine? if so, try using C4pre instead of C3.
