### ISSUE TITLE
Death trap FYI

### ISSUE THREAD

**Issue by PONYRYDE** [BreakfastCraft/Spilled-Juice-Modpack#70]
Using Spilled Juice 0.2.3 in SSP I died to an Enderman and was not able to respawn even after deleting player dat. Log mentioned something about TombManyGraves. Updating to latest (2.1.11) resolved the issue which seemed to be related to Baubles.

Thanks for the great modpack and all the effort you have put into it.

**Comment by slidingmike** [comment]
I think this resolve some issues I've heard of similar to you. I'll see if we can push a hotfix

**Comment by UnNinja** [comment]
0.2.3.1 will be live about 10 minutes from now, it contains tmg 2.1.11 along with a couple of other updates to clear nag messages (which we normally ignore, but since we're updating anyway...). Thanks for letting us know about this

**Comment by UnNinja** [comment]
Or not. Issue persisted on our servers even with latest TMG. We have removed said mod until they're able to fix this problem, or we find another grave mod that plays nice with the baubles betas

**Comment by PONYRYDE** [comment]
I haven't been able to replicate the issue since, still using 0.2.3.
While testing though I found a possibly related bug https://github.com/M4thG33k/TombManyGraves/issues/23

**Comment by slidingmike** [comment]
Seems to be fixed minus on our own server world. This has been closed.
