### ISSUE TITLE
Add liquids for railcraft config

### ISSUE THREAD

**Issue by StaticPH** [BreakfastCraft/Spilled-Juice-Modpack#72]
If people want to submit tickets for config changes, its a lot easier to do if the configs in the github repository are the same as the default configs for the pack. Or at least if all the configs in the pack _exist_ in the repository.

**Comment by UnNinja** [comment]
probably some config changes, and at least one config regeneration, in the next update. I'll remind mike to fix the thing after that goes out

**Comment by StaticPH** [comment]
While we're at it, any chance of enabling "allowLiquids" in the railcraft config?

**Comment by slidingmike** [comment]
What's that do?

**Comment by UnNinja** [comment]
No

**Comment by StaticPH** [comment]
It lets you put cells and cans of fluid in chest carts.

**Comment by slidingmike** [comment]
Why

**Comment by UnNinja** [comment]
Tank carts exist. why do we need this

**Comment by slidingmike** [comment]
I'm fine with adding it UnNinja. Tank cars are a bit limited right now, and being able to increase the amount moved, would be nice. Not to mention the added cost, and having to build a setup to extract from those items, I believe makes it balanced.

I would however look and see if we can change stack qty to balance it even more. 64 cells at 27 slots is a bit overpowered.

I'll take a look at this either tonight, or later this week. Ninja, mark this as enhancement, 1.10.2, and then assign to me please @UnNinja
