### ISSUE TITLE
Mod Suggestion for the Builders...

### ISSUE THREAD

**Issue by Winrylive** [BreakfastCraft/Spilled-Juice-Modpack#73]
Flat Colored Blocks

https://minecraft.curseforge.com/projects/flat-colored-blocks

Pretty please?

**Comment by UnNinja** [comment]
Added in 0.2.5 (dropping some time next week unless something explodes)

**Comment by slidingmike** [comment]
I pulled this from 2.X because of some lag concerns from textures.

**Comment by UnNinja** [comment]
Whenever I figure out what's breaking 2.5 and we're able to push, FCB will have been tweaked to have fewer colors. Compromise between having it and reducing texture-related issues
