### ISSUE TITLE
Serverside crash when trying to launch pack version 2.5.1

### ISSUE THREAD

**Issue by Ozimundis** [BreakfastCraft/Spilled-Juice-Modpack#78]
http://pastebin.com/yraMTxYA

Updated our server to 2.5.1 after having no success getting 2.5 working, due to forge not updating with the rest of the pack, and other mod incompatibility, now this happens whenever I try to launch our server. 
Leaving this here for the night, will check back tomorrow (UK time.)

**Comment by UnNinja** [comment]
I missed a bracket in the initial xml for 2.5.1. A reinstall should resolve this issue

**Comment by Ozimundis** [comment]
I'm unsure, do you mean a re-install of 2.5.1?  As that didn't work. I tried deleting the mod and config folder, but when it reinstalled, it still threw up a server error. 
 Neither does the 2.5 version. It seems not to want to install the correct version of forge alongside the pack update, and if i manually add forge, It still gives me mod incompatibles when i try to log in.

**Comment by Ozimundis** [comment]
So, with help of a friend who knows this far better than I do, we have tried the following

Tried deleting all files bar our world file, then re-installing 2.5.1, no work. 
Tried the same with 2.5 and a fresh client install, didn't work either, got mod incompatabilies. 

Tried doing this on both, our main server instance, and a fresh, testing instance for this.

**Comment by UnNinja** [comment]
What version of FTButilities and FTB Lib are on the server? 2.5.1 should be installing version 3.11 of each

**Comment by Ozimundis** [comment]
Those are the installed versions. 
I'll be honest, after a good hour trying things yesterday, we've decided to move away from Spilled Juice, temporarily. 
I'll keep this ticket open, to see if we can get to the bottom of this, but as we're not actively playing the pack, I'll understand if you want to close it. In which case, I'll just keep my eye on the ATL page, and try again when you do your next batch of updates.

**Comment by slidingmike** [comment]
No reason to fee bad about that decision. We respect it and didn't expect to Juice to grab the attention it did. Unfortunately we are down a developer due to some real life issues and are struggling to identify what is causing so many problems in the 2.5 update. This is actually the 4th attempt we've had trying to straighten it out, but no luck so far.

This ticket will stay open as a source of information while we continue to investigate. We apologize for the inability of solving it so far, but be assured we will continue to achieve stability especially amongst the developments of 1.10.2

**Comment by Ozimundis** [comment]
Not a problem dude, we are actually really enjoying the pack, to be fair, out of the 1.10 packs we have available, It's the most rich and "Fullest" if that makes sense. 
If we can help out to diagnose the issue more I'd gladly offer what (limited) assistance I can. 
As for the real life issues, best of luck to the person involved and hope things go well!
