### ISSUE TITLE
[Mod Suggestion] Astral Sorcery

### ISSUE THREAD

**Issue by Winrylive** [BreakfastCraft/Spilled-Juice-Modpack#86]
I don't know how far advanced a mod needs to be to consider it for addition, but a Beta release of a new magic mod just came out that I'm curious to look at

https://minecraft.curseforge.com/projects/astral-sorcery

**Comment by UnNinja** [comment]
Looks neat. Will probably add it in 3.2. Going to leave this open so I don't forget about it
