### ISSUE TITLE
Pack Loading Hangs

### ISSUE THREAD

**Issue by Winrylive** [BreakfastCraft/Spilled-Juice-Modpack#87]
So, loading is slow anyway I know, but there's no reason why it should hang for **over 5 mins** at one spot. Screenshot is console and where the pack is when it happens. It sits at that entry for the whole time as if it's stuck and then eventually keeps going. Note the console time and my computer time.... I think Demethan also noted yesterday that the pack loading was really slow. Can we figure out why?

![stuck](https://cloud.githubusercontent.com/assets/17501344/23323281/94092584-faad-11e6-93dd-bab1baba9379.png)

**Comment by UnNinja** [comment]
This appears to be resolved in 0.33
