### ISSUE TITLE
Astral Sorcery: Luminous crafting impossible

### ISSUE THREAD

**Issue by Xarbaros** [BreakfastCraft/Spilled-Juice-Modpack#88]
To use the majority of Astral Sorcery, you need to create a Luminous Crafting Table and Resonating Wand. Both should be createable by placing a standard Crafting Table near one of the Floating Crystals found in the big marble wells the mod generates (refer to the Journal). If done so, a beam of light should radiate to the table and the recipies become craftable. This does not happen in 0.3.3, it did however seem to work in 0.3.2.
![as](https://cloud.githubusercontent.com/assets/26447309/23976848/cce5c6a4-09ea-11e7-81e9-e92426e4f130.jpg)

**Comment by topher2010** [comment]
New modpack being developed, this version is no longer supported.
