### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by Xarbaros** [BreakfastCraft/Spilled-Juice-Modpack#89]
Since the Spilled Juice server updated to 0.3.3 there has been a galore of crashes. From what I gathered, a few of the reasons seem to be: Swimming, approaching certain locations, standing still for too long, causing a chunk update. Or maybe it doesn't have to do anything with all that. Any info on what is going on?

**Comment by UnNinja** [comment]
Can you post the crash log(s) please?

**Comment by Xarbaros** [comment]
I cannot. Maybe it was not clear enough, but was talking about the server crashing, or at least forcibly terminating all client connections. Playing Singleplayer works for the most part.

**Comment by topher2010** [comment]
New modpack being developed, this version is no longer supported.
