### ISSUE TITLE
[0.04] install One True Probe or equivalent to get tooltips on blocks you're facing

### ISSUE THREAD

**Issue by mote** [BreakfastCraft/Spilled-Juice-Modpack#93]

**Comment by topher2010** [comment]
TheOneProbe is in the modpack

**Comment by mote** [comment]
It doesn't seem to be configured properly. I was able to get tooltips to show up for me by cheating in a probe and configuring it from there.

Let me debug further on my end.

**Comment by mote** [comment]
Ugh, a new world doesn't have this problem. I guess we can wait to see if this is an issue with anyone else.

**Comment by slidingmike** [comment]
I've tested again and i've not been able to replicate it not working. Not sure what occurred here, but we'll wait and see if we get any other instances to revisit this.
