### ISSUE TITLE
[0.04] Don't see any other better-than-vanilla-manual-mining besides IC2 drills

### ISSUE THREAD

**Issue by mote** [BreakfastCraft/Spilled-Juice-Modpack#94]

**Comment by topher2010** [comment]
Aether Legacy, AE2, Astral Sorcery, Botania, Industrial Foregoing, Immersive Engineering, Mekanism, Roots, Thaumcraft all have some form of mining that goes beyond vanilla manual mining.  If you have an idea for a mod to add (that isn't Tinker's) please drop a new issue requesting that mod and we can look into it.
