### ISSUE TITLE
Astral Sorcery Ore Cave

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#97]
Not sure if there is a config to prevent the two type of tin and silver etc.  
![image](https://user-images.githubusercontent.com/5810363/68820136-5c152600-0658-11ea-9ecc-9e86feb060f1.png)

**Comment by slidingmike** [comment]
There was a config issue on our initial server load. Old world gen has the duplicate ores but if you travel further out, this issue doesn’t exist anymore
