### ISSUE TITLE
Hide facades from AE

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/Spilled-Juice-Modpack#99]
We don't need to see all the facade in JEI.

**Comment by slidingmike** [comment]
Dunno if there’s an easy way to fix this

**Comment by Winrylive** [comment]
JEI allows you to hide items. A lot of pack makers do that for tinker's parts too.

https://www.reddit.com/r/feedthebeast/comments/adb53c/jei_item_hiding/

**Comment by slidingmike** [comment]
This has been completed.
